name: Build DEB

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Build Tweak
        run: |
          mkdir -p build/DEBIAN
          cp ElegIsland_Csomag/DEBIAN/control build/DEBIAN/
          mkdir -p build/var/jb/Library/Widgets/Universal/ElegIsland
          cp ElegIsland_Csomag/var/jb/Library/Widgets/Universal/ElegIsland/Widget.html build/var/jb/Library/Widgets/Universal/ElegIsland/
          dpkg-deb --build build ElegIsland.deb

      - name: Commit DEB
        run: |
          git config --global user.name 'GitHub Action'
          git config --global user.email 'action@github.com'
          git add ElegIsland.deb
          git commit -m "Automated DEB Build" || exit 0
          git push
